In [4]:
import numpy as np

In [18]:
#Tạo và in mảng
arr = np.array([51, 100, 49, 12, 50])
print(arr)

[ 51 100  49  12  50]


In [24]:
#In ra một phần tử
elm = arr[2]
print(elm)

49


In [32]:
#Tạo mảng 2 chiều
arr2c = np.array([[2, 5],[1, 6],[9, 4],[3, 7]])
print(arr2c)

[[2 5]
 [1 6]
 [9 4]
 [3 7]]


In [40]:
#In ra một phần tử
elm = arr2c[2]
print(elm)

[9 4]


In [ ]:
#Cách tạo mảng nhanh

In [48]:
#Tạo mảng full 0
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [50]:
#Tạo mảng full 1
arr = np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [ ]:
#Tạo mảng
arr = 